### ISSUE TITLE
[Nhóm#9] - lỗi chức năng - Không thể kết nối do quá thời gian, máy chủ không phản hồi  - Ở trang http://digital.lib.ueh.edu.vn

### ISSUE THREAD

**Issue by leanhnhat1997** [UEHMonQAQC/K41#100]
a. Web Browser: Chrom Version 66.0.3359.139 (Official Build) (64-bit)
b. Các bước để phát hiện lỗi:
i. #1: Đối với tất cả các tài liệu ở mục URL nếu có Link dạng " http://opac.ueh.edu.vn/record=..." ví dụ http://opac.ueh.edu.vn/record=b1026511~S1 trong trang này: http://digital.lib.ueh.edu.vn/handle/UEH/57148 thì khi truy cập đều sẽ bị lỗi Timeout
![image](https://user-images.githubusercontent.com/28390980/39748521-787a06ea-52da-11e8-9313-b0177c1f6b10.png)
c. Kết quả thực tế:
![image](https://user-images.githubusercontent.com/28390980/39748741-0d255dee-52db-11e8-9d18-81c51aba44b6.png)
d. Kết quả mong đợi: Máy chủ phản hồi và trả về nội dụng của Link đó

**Comment by 31151024226** [comment]
Đã kiểm tra, khi nhấn vào link vẫn load ra trang bình thường ngay lập tức
