### ISSUE TITLE
[Nhóm#9] Lỗi Phi chức năng - Lỗi tốc độ truy cập- http://lib.ueh.edu.vn

### ISSUE THREAD

**Issue by hoangnguyenhitech** [UEHMonQAQC/K41#104]
a. Web Browser: Chrome Phiên bản 66.0.3359.139 
b. Các bước để phát hiện lỗi:
i. #1: Truy cập http://lib.ueh.edu.vn/vi/th%C3%B4ng-b%C3%A1o/th%C3%B4ng-b%C3%A1o-l%E1%BB%8Bch-ngh%E1%BB%89-l%E1%BB%85-gi%E1%BB%97-t%E1%BB%95-h%C3%B9ng-v%C6%B0%C6%A1ng-l%E1%BB%85-30-th%C3%A1ng-4-v%C3%A0-01-th%C3%A1ng-5-n%C4%83m-2018
ii. #2: Tốc độ truy cập lâu và đôi khi bị đứng phải load lại trang
c. Kết quả thực tế: (đã chiếu hình)
d. Kết quả mong đợi: Tốc độ tải trang nhanh hơn và tải chỉ một lần là được.
![untitled](https://user-images.githubusercontent.com/38711947/39749547-2bc91e5a-52dd-11e8-982a-1220ccea6f10.png)

**Comment by 31151024226** [comment]
Đã kiểm tra và tốc độ truy cập nhanh, load file ngay lập tức
