### ISSUE TITLE
[ Nhóm #10] - Lỗi giao diện ở trang – chữ viết sai chính tả:  http://www.lib.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31151020883** [UEHMonQAQC/K41#109]
a. Web browser: Cốc cốc Phiên bản 68.4.194.
b. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang http://www.lib.ueh.edu.vn
ii. #2: Kéo xuống mục search, .để tìm sách
c. Kết quả thực tế: chữ viết sai chính tả.
d. Kết quả mong đợi: chữ viết đúng chính tả.
![2](https://user-images.githubusercontent.com/38751373/39759785-c52655e8-52fd-11e8-889f-2c9c072c9c4e.png)

**Comment by 31151023198** [comment]
http://vtv.vn/su-kien-va-binh-luan/gs-ts-nguyen-quang-dong-ky-xet-tuyen-dai-hoc-cao-dang-2015-dat-4-thanh-tuu-lon-20150822111930499.htm
Nguyễn Quang Dong là tên đúng của thầy nhe bạn.
Còn Nguyễn, Thị Minh, PGS.TS.,đồng chủ biên là format tác giả của web, không phải lỗi.
