### ISSUE TITLE
[Nhóm #8] - Lỗi Chức năng - Lỗi không xem được phim trang: http://www.studyphim.vn

### ISSUE THREAD

**Issue by 31151024160** [UEHMonQAQC/K41#119]
a. Web browser: Google Chrome Version 66.0.3359.139
b. Các bước phát hiện lỗi:
i. #1: Vào **Tìm kiếm phim** và search **Grey's Anatony (season 13)**
![cn 2](https://user-images.githubusercontent.com/38709358/39802540-8714d9fa-5398-11e8-9386-1cdcd5d427b8.png)
ii. #2: Truy cập vào phim
c. Kết quả thực tế: Không xem được phim. Link phim hiện lỗi server 404.
![cn 4](https://user-images.githubusercontent.com/38709358/39802644-c5383fa6-5398-11e8-8ce6-ff7e7381b353.png)

d. Kết quả mong đợi: Xem được phim.

**Comment by 31151024226** [comment]
Đã check và vẫn xem được phim
