### ISSUE TITLE
[Nhóm#3]- Lỗi chức năng - Lỗi không gửi thắc mắc được ở trang http://youth.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31151021451** [UEHMonQAQC/K41#131]
a. Web browser: Cốc Cốc Phiên bản 68.4.194
b. Các bước để phát hiện lỗi:
i.#1: Truy cập trang http://youth.ueh.edu.vn/
ii.#2: Chọn mục Chức năng
iii.#3: Chọn Hệ thống mã vạch
iv.#4: Chọn Liên hệ trong khung Danh mục
v.#5: Chọn gửi thắc mắc
c. Kết quả hiện tại:
<img width="463" alt="capture3" src="https://user-images.githubusercontent.com/38746437/39825605-5cbf9b38-53dc-11e8-8859-1bef6c7f0741.PNG">
d. Kết quả mong muốn:
Đến được trang có thể gửi thắc mắc cho 1 cá nhân hay đơn vị cụ thể

**Comment by viethieule** [comment]
Lỗi này trùng với lỗi #132 nhóm đã post trước đó nha
