### ISSUE TITLE
[Nhóm#3] - Lỗi chức năng - Lỗi liên kết không hoạt động ở trang http://www.youth.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31151021451** [UEHMonQAQC/K41#135]
a. Web browser: Cốc Cốc Phiên bản 68.4.194
b. Các bước để phát hiện lỗi:
i.#1: Truy cập trang http://youth.ueh.edu.vn/
ii.#2: Chọn mục Chức năng
iii.#3: Chọn Rèn luyện Đoàn viên
iv.#4: Nhập đúng tên đăng nhập và mật khẩu sau đó click Đăng nhập
v.#5: Chọn tag Bình chọn
c. Kết quả hiện tại:
<img width="933" alt="capture5" src="https://user-images.githubusercontent.com/38746437/39826346-8cdc84a0-53de-11e8-8733-c9e3c193604b.PNG">
d. Kết quả mong muốn:
Link hoạt động được và có nội dung

**Comment by viethieule** [comment]
Lỗi này trùng với lỗi #77 nhóm đã post nha
