### ISSUE TITLE
[Nhóm#3] - Lỗi phi chức năng - Lỗi tương thích lượt xem ở trang http://youth.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31151021451** [UEHMonQAQC/K41#140]
a. Web browser: Cốc Cốc Phiên bản 68.4.194
b. Các bước để phát hiện lỗi:
i.#1: Truy cập trang http://youth.ueh.edu.vn/
ii.#2: Chọn Liên hệ
iii.#3: Chọn Thắc mắc, giải đáp
iv.#4: Kéo xuống cuối trang bên phải có khung SỐ LƯỢT XEM
v.#5: F5 trang hoặc thoát ra lặp lại các bước trên
c. Kết quả hiện tại:
Luôn luôn xuất hiện 3403193 lượt xem
<img width="253" alt="capture8" src="https://user-images.githubusercontent.com/38746437/39827487-3eef61f0-53e2-11e8-9943-f1627e2de27f.PNG">
d. Kết quả mong muốn:
Mỗi lần truy cập sẽ nhảy lên 1 lượt xem

**Comment by viethieule** [comment]
Lỗi này không thuộc trang của UEH vì khi bấm vào thắc mắc, giải đáp sẽ được chuyển qua trang hoisinhvientphcm.com và số lượt xem nằm trên trang đó
