### ISSUE TITLE
[Nhom#5] Lỗi chức năng-Không nhấn chuột được vào nút Thông báo- ở trang http://rmic.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31151022641** [UEHMonQAQC/K41#148]
a.	Web Browser: Google Chrome Version 66.0.3359.139 (64-bit)
b.	Các bước phát hiện lỗi:
i.	#1 Truy cập vào trang http://rmic.ueh.edu.vn/ 
ii.	#2 kéo chuột vào Nhà Kinh Tế trẻ UEH 2018
iii.	#3 Nhấn vào Thông Báo
 
![image](https://user-images.githubusercontent.com/38519964/39882251-76316eb2-54ad-11e8-814e-32f773589046.png)

c.	Kết quả thực tế: Không có hiện tượng gì xảy ra
 
![image](https://user-images.githubusercontent.com/38519964/39882257-7a8a04e2-54ad-11e8-8b91-7ccbebd9096a.png)

d.	Kết quả mong đơi: hiện ra thông tin về thông báo cần xem

**Comment by 31151021507** [comment]
Xem lại lỗi này là chức năng nhé
