### ISSUE TITLE
Nhóm#3]-Lỗi chức năng-trang chủ mục tin nổi bật -Ở trang http://youth.ueh.edu.vn/ 

### ISSUE THREAD

**Issue by RicNguyen287** [UEHMonQAQC/K41#154]
a.Web Browser: Google Chrome Phiên bản 66.0.3359.139 (Phiên bản Chính thức) (64 bit)
b. Các bước để phát hiện lỗi:
i.#1: Truy cập trang http://youth.ueh.edu.vn/
ii.#2: Di chuột xuống mục "Tin nổi bật"
iii.#3: Chọn link " Thông tin tuyển dụng Trung Nguyên E-Coffee"
![image](https://user-images.githubusercontent.com/38519893/39857819-e2719b64-545e-11e8-8828-4a4a17dba230.png)
iv.#4: Click tiếp link  " Thông tin tuyển dụng Trung Nguyên E-Coffee" 2 đến 3 lần ở mục "Tin nổi bật" góc bên phải
![image](https://user-images.githubusercontent.com/38519893/39858109-c2625128-545f-11e8-8b92-d69e3f3e8fc6.png)
v.#5: Chọn bất kì các mục, liên kết khác ở "Tin nổi bật"
c. Kết quả hiện tại:
Các liên kết đó không hoạt động
![image](https://user-images.githubusercontent.com/38519893/39858200-0cbe5438-5460-11e8-9600-4516326fddda.png)
d. Kết quả mong muốn:
Các link sẽ hoạt động bình thường dù nhấp bao nhiêu lần

**Comment by tuannmueh** [comment]
Đây không phải lỗi phi chức năng nên bị bỏ qua
