### ISSUE TITLE
[Nhóm#3] - Lỗi chức năng - Lỗi liên kết ở trang youth.ueh.edu.vn

### ISSUE THREAD

**Issue by 31151021451** [UEHMonQAQC/K41#156]
a. Web browser: Cốc Cốc Phiên bản 68.4.194
b. Các bước để phát hiện lỗi:
i.#1: Truy cập trang http://youth.ueh.edu.vn/
ii.#2: Chọn mục Chức năng
iii.#3: Chọn Danh sách Đoàn viên - Hội viên
iv.#4: Kéo xuống cuối trang
v.#5: Chọn bất kỳ 1 trong 4 liên kết sau
<img width="166" alt="capture8" src="https://user-images.githubusercontent.com/38746437/39858491-f527eb62-5460-11e8-84b1-8828df41b6a0.PNG">
c. Kết quả hiện tại:
Trả về đầu trang
d. Kết quả mong muốn:
Liên kết được thực hiện đến các link mạng xã hội tương ứng

**Comment by viethieule** [comment]
Lỗi phần footer ở cuối trang Youth này trùng với lỗi #15 nhóm đã post nha. Footer xài chung trong cả trang youth (trong html là footer class="footer-distributed" đều giống nhau.
