### ISSUE TITLE
[Nhom#5] Lỗi chức năng-Chức năng tìm kiếm không hoạt động- ở trang http://rmic.ueh.edu.vn/ 

### ISSUE THREAD

**Issue by 31151022641** [UEHMonQAQC/K41#169]
a.	Web Browser: Google Chrome Version 66.0.3359.139 (64-bit)
b.	Các bước phát hiện lỗi:
i.	#1 Truy cập vào trang http://rmic.ueh.edu.vn/ 
 
![image](https://user-images.githubusercontent.com/38519964/39881250-971af7d6-54aa-11e8-89c3-8cd5857366e4.png)

ii.	#2 Nhập nội dung tìm kiếm và nhấp vào biểu tượng tìm kiếm
 
![image](https://user-images.githubusercontent.com/38519964/39881258-9e16c9d4-54aa-11e8-8d99-f5c89971ae46.png)

iii.	#3 không xảy ra hiện tường gì
c.	Kết quả thực tế: không tìm kiếm được
d.	Kết quả mong đơi: tìm kiếm được nội dung cần tìm

**Comment by 31151021507** [comment]
Kiểm tra lại mình vẫn tìm kiếm được từ khóa
