### ISSUE TITLE
[Nhom#5] Lỗi chức năng-không hiên dấu tick ghi nhớ ở lần đăng nhập sau- ở trang http://www.ctct.ueh.edu.vn/ 

### ISSUE THREAD

**Issue by 31151022641** [UEHMonQAQC/K41#27]
e.	Web Browser: Google Chrome Version 66.0.3359.139 (64-bit)
f.	Các bước phát hiện lỗi:
i.	#1 Truy cập vào trang http://www.ctct.ueh.edu.vn/
ii.	#2 Chọn Chức năng/Tài khoản rèn luyện
iii.	#3 Nhập 'Mã số sinh viên' và 'Mật khẩu'
iv.	 #4 Tick vào dấu 'Ghi nhớ ',xuất hiện dấu Tick và lưu 'Ma số sinh viên' và 'Mật khẩu’
 
![image](https://user-images.githubusercontent.com/38519964/39684133-e5baca7a-51e3-11e8-8a86-241fb6577b47.png)

v.	#5 Đăng thoát
vi.	#6 Mật khẩu và mã số sinh viên được lưu nhưng không hiện dấu tick trong Ghi nhớ
g.	Kết quả thực tế: Không xuất hiện dấu Tick nhưng vẫn lưu được 'Tên đăng nhập' và 'Mật mã'
 
![image](https://user-images.githubusercontent.com/38519964/39684138-ec0d4fba-51e3-11e8-8664-5bf50ba84041.png)

h.	Kết quả mong đợi: Phải xuất hiện dấu Tick để biết có trạng thái 'Ghi nhớ'

**Comment by 31151021507** [comment]
khi đăng thoát thì các trường username password sẽ để blank trở lại, mục đích là cho người dùng đăng nhập lại một tài khoản khác, nhưng browser (chrome) nó ghi nhớ trường ghi nhớ cũng theo đó mà unchecked.
