### ISSUE TITLE
 [Nhom#5] Lỗi chức năng-Không thể truy cập liên kết Nghị quyết số 29 - ở trang http://www.ctct.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31151022641** [UEHMonQAQC/K41#31]
a.	Web Browser: Google Chrome Version 66.0.3359.139 (64-bit)
b.	Các bước phát hiện lỗi:
i.	#1 Truy cập vào trang http://www.ctct.ueh.edu.vn/
ii.	#2 nhấp vào hình ảnh: Nghị quyết số 29…..
 
![image](https://user-images.githubusercontent.com/38519964/39684643-8f5cb400-51e7-11e8-9bc5-f9281d35d9c0.png)

iii.	#3 Hiện ra 1 trang web mới nhưng không thấy được nội dung.
iv.	 #4 Nhìn thấy dòng chữ : not found
c.	Kết quả thực tế: Không xuất hiện nội dung chi tiết chương trình cần xem
 
![image](https://user-images.githubusercontent.com/38519964/39684647-93214452-51e7-11e8-8fea-83603b940f6b.png)

d.	Kết quả mong đợi: Xuất hiện trang liên kết với nội dung nghị quyết số 29.

**Comment by 31151021507** [comment]
Lỗi chức năng nha.
