### ISSUE TITLE
[Nhóm#2]Lỗi chức năng-Liên kết không hoạt động

### ISSUE THREAD

**Issue by 31151021606** [UEHMonQAQC/K41#40]
a. Web browser: google chrome
b. Các bước để phát hiện lỗi:
 i. #1: Truy cập vào trang : http://alumni.ueh.edu.vn
ii. #2:Chọn mục ƯU ĐÃI THÀNH VIÊN
 iii.#3. Không hiển thị nội dung
c. Kết quả thực tế: Không có gì thay đổi khi chưa nhấn và đã nhấn
d. Kết quả mong đợi: Hiển thị nội dung trong phần đó
![image](https://user-images.githubusercontent.com/38643390/39686274-4ec1d456-51f2-11e8-80c4-23c8e2ce6dd3.png)

**Comment by viethieule** [comment]
Lỗi này bị trùng với lỗi #45 nha.
