### ISSUE TITLE
[Nhóm#2]Lỗi giao diện-màu sắc khó phân biệt 

### ISSUE THREAD

**Issue by 31151021606** [UEHMonQAQC/K41#49]
a.Web browser: google chrome phiên bản 65.0.3325.181
b.Các bước phát hiện lỗi:
i.#1: Truy câp website http://alumni.ueh.edu.vn
ii.#2: Đưa con trỏ chuột tới mục GIỚI THIỆU
iii.#3: Màu sắc khó phân biệt 
c.Kết quả thực tế: Màu sắc khó phân biệt làm người truy cập không dễ dàng nhận biết mình đang chọn mục nào
d.Kết quả mong đợi: Màu sắc dễ phân biệt giúp người truy cập nhận biết dễ dàng
![image](https://user-images.githubusercontent.com/38643390/39687190-699285fa-51f7-11e8-8383-49c4ca6d5474.png)

**Comment by viethieule** [comment]
Màu sắc này theo mình không khó để phân biệt và người dùng vẫn có thể dễ dàng click được nha, Vì vậy nên đây không phải là lỗi.
