### ISSUE TITLE
[Nhóm#10] - lỗi chức năng-liên kết không hoạt động: http://youth.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31151020089** [UEHMonQAQC/K41#68]
a. Web browser: Cốc cốc Phiên bản 68.4.194.
b. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang http://www.youth.ueh.edu.vn
ii. #2: Kéo xuống mục Sinh viên 5 tốt , chọn Tình nguyện tốt , mở liên kết [CDTN SVKT2017] SÓC TRÀO YÊU THƯƠNG
![13](https://user-images.githubusercontent.com/38519917/39702746-fc68de46-522f-11e8-8dd5-e9fb8e06771a.png)

c. Kết quả thực tế: Lỗi liên kết không hoạt động.
d. Kết quả mong đợi: Liên kết hoạt động và có nội dung.

**Comment by 31151023198** [comment]
Mình không thấy liên kết [CDTN SVKT2017] SÓC TRÀO YÊU THƯƠNG ở đâu cả.
