### ISSUE TITLE
[NHÓM#10] – Phi chức năng – Lỗi ở tính bảo mật - Ở trang http://youth.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31151020089** [UEHMonQAQC/K41#74]
1.Web browser: UC Browser version 7.0.185.1002
2. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang http://www.youth.ueh.edu.vn
ii. #2: Chọn mục Chức năng
iii #3: Nhấp vào Rèn luyện đoàn viên
iv #4: Đăng nhập tài khoản
v #5: Chọn mục Đăng thoát
![19](https://user-images.githubusercontent.com/38519917/39705070-8704f9e8-5237-11e8-8c27-0c070c2a5bb2.png)

3. Kết quả thực tế: Tên đăng nhập và mật khẩu được lưu lại
4. Kết quả mong muốn: Không cho phép lưu tên đăng nhập và mật khẩu

**Comment by 31151023198** [comment]
Mình làm thử các bước và tài khoản mình không có lưu như kết quả của bạn nha!
