### ISSUE TITLE
[Nhóm#3]-Lỗi liên kết-Mục đối tác -Ở trang http://youth.ueh.edu.vn/ (#9)

### ISSUE THREAD

**Issue by 31151021602** [UEHMonQAQC/K41#85]
a.Web Browser: Google Chrome Phiên bản 66.0.3359.139 (Phiên bản Chính thức) (64 bit)
b. Các bước để phát hiện lỗi:
i.#1: Truy cập trang http://youth.ueh.edu.vn/
ii.#2: Kéo xuống gần cuối 
iii.#3: Chọn mục đối tác 
c. Kết quả hiện tại
![image](https://user-images.githubusercontent.com/30387688/39709534-55ee9406-5244-11e8-9039-3edd8ad819f2.png)
Click vào bị đưa lên lại đầu trang 
d. Kết quả mong muốn:
sẽ liên kết đến trang đối tác không phải là trang chủ

**Comment by viethieule** [comment]
Đây không phải là lỗi phi chức năng. Có thể đây là lỗi chức năng vì không có chức năng nào được thực hiện mà liên quan tới nội dung được hiển thị này
